### ISSUE TITLE
Feature Request: Robust Error Handling

### ISSUE THREAD

**Issue by ElijahSwiftIBM** [ambitus/pyracf#12]
**Is your feature request related to a problem? Please describe.**
-pyRACF ignores unknown fields and traits passed into it, this can cause problems if output it not closely monitored for validation
-pyRACF also allows "bad" or "invalid" data types to be passed to RACF, which will throw a security request error on failure
-pyRACF's ADD and ALTER requests are not mutually exclusive. ADD can inadvertently ALTER existing users, and ALTER can create new ones

**Describe the solution you'd like**
-pyRACF should validate these fields and traits, and throw errors for unknowns
-pyRACF should throw its own errors for obviously invalid data before it is passed to RACF
-pyRACF's ADD and ALTER functions should check to ensure ADD will not ALTER an existing user and ALTER will not ADD a new one

**Additional context**
IRRSMO00 has a flag for TERMINATE ON FIRST ERROR which will likely stop ADD from altering an existing user as long as ADD does not use the PRECHECK flag.

**Comment by lcarcaramo** [comment]
Resolved by #26 and #27
