### ISSUE TITLE
Create GitHub actions linting and unit test automation using the existing .travis.yml as a template.

### ISSUE THREAD

**Issue by lcarcaramo** [ambitus/pyracf#2]
Since GitHub actions is built into GitHub, it probably makes sense to use GitHub Actions instead of Travis for pyRACF listing and unit test automation.
* GitHub Actions documentation: https://docs.github.com/en/actions

**Comment by ElijahSwiftIBM** [comment]
Pull Request #7 has been opened to address this concern.

**Comment by lcarcaramo** [comment]
PR merged.
