### ISSUE TITLE
Convert setup.py to pyproject.toml

### ISSUE THREAD

**Issue by lcarcaramo** [ambitus/pyracf#3]
Since `setup.py` is now considered deprecated, we should convert the pyRACF `setup.py` build configuration to `pyproject.toml`.

* Info about `setup.py` being deprecated: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary
* Documentation for `pyproject.toml`: https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

**Comment by ElijahSwiftIBM** [comment]
Pull request #8 has been opened to address this concern

**Comment by lcarcaramo** [comment]
PR #8 merged.
