### ISSUE TITLE
Bug Report: SegmentError and SegmentTraitError keep built dictionaries

### ISSUE THREAD

**Issue by ElijahSwiftIBM** [ambitus/pyracf#33]
**Describe the bug**
SegmentError and SegmentTraitError exit the code without clearing segment trait dictionaries. This leads to improper request dictionaries built on the next request.

**To Reproduce**
Make a request that will encounter SegmentTraitError or SegmentError. Make another request incompatible with those traits.

**Expected behavior**
These requests should be independent of one another if at all possible

**Console Output**
N/A

**Environment Information:**
 - IBM Python 3.11 on z/OS 2.4

**Additional context**
N/A

**Comment by lcarcaramo** [comment]
Resolved by: #34
