### ISSUE TITLE
Bug Report: Resource Profile Subfunctions extract "" as "" and not as null

### ISSUE THREAD

**Issue by ElijahSwiftIBM** [ambitus/pyracf#37]
**Describe the bug**
Resource Profile Subfunctions extract "" as "" and not as null

**To Reproduce**
Set a trait like grouping_class_name to "" in a resource profile and extract it with any applicable profile extract function.

**Expected behavior**
This should be cast to null rather than left as an empty string

**Console Output**
Visible in unit tests and documentation for resource profile subfunctions

**Environment Information:**
N/A

**Additional context**
N/A

**Comment by lcarcaramo** [comment]
resolved by #38 and #39
