### ISSUE TITLE
Feature Request: Install Script/Documentation Improvements

### ISSUE THREAD

**Issue by ElijahSwiftIBM** [ambitus/pyracf#48]
**Is your feature request related to a problem? Please describe.**
Users are having issues with the setup and definition of the `IRR.IRRSMO00.PRECHECK` resource in the `XFACILIT` class. 

**Describe the solution you'd like**
We should potentially have a script that could define this resource so that auditing would flag attempts to use it when it fails. 

**Describe alternatives you've considered**
Another alternative would be to DIRECTLY REFERENCE this general resource in the install steps in the documentation.

**Additional context**
N/A

**Comment by lcarcaramo** [comment]
Implemented in #57
