### ISSUE TITLE
Feature Request: EXPIRED/NOEXPIRED option on set_password and set_passphrase

### ISSUE THREAD

**Issue by ElijahSwiftIBM** [ambitus/pyracf#49]
**Is your feature request related to a problem? Please describe.**
set_password and set_passphrase options currently don't have the option to set non-expired passwords.

**Describe the solution you'd like**
We should add an optional argument to these functions to make the password non-expired.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lcarcaramo** [comment]
Resolved by #55
