### ISSUE TITLE
Feature Request: Improved Secrets redaction

### ISSUE THREAD

**Issue by ElijahSwiftIBM** [ambitus/pyracf#6]
IRRSMO00 has an optional feature already to redact secret fields, and customers may also have fields beyond passwords and password phrases that require redaction. Both of these are features we should implement for additional security with pyRACF

**Comment by ElijahSwiftIBM** [comment]
Created pull request #9 to address this concern

**Comment by lcarcaramo** [comment]
PR9 merged.
