### ISSUE TITLE
Bug Report: SecurityRequestError Doc references out of date

### ISSUE THREAD

**Issue by ElijahSwiftIBM** [ambitus/pyracf#61]
**Describe the bug**
Documentation error in 1.0b3. Numerous functions document SecurityRequestError as 

`Raises `SecurityRequestError` when the **Return Code** of a **Security Result** returned by IRRSMO00 is **NOT** equal to `0``

This needs to be updated and all functions capable of raising SecurityRequestError in this way can also raise DownstreamFatalError as well.

**To Reproduce**
N/A

**Expected behavior**
Change documentation to

`Raises `SecurityRequestError` when the **Return Code** of a **Security Result** returned by IRRSMO00 is equal to `4``

also include comparable documentation for DownstreamFatalError

**Console Output**
N/A

**Comment by lcarcaramo** [comment]
Resolved by #62
