### ISSUE TITLE
Bug Report: Current Documentation (RunAsUserID feature) missed changes to ResourceAdmin Documentation

### ISSUE THREAD

**Issue by ElijahSwiftIBM** [ambitus/pyracf#72]
**Describe the bug**
ResourceAdmin documentation has abstraction `get_your_access` when the feature(s) are `get_my_access` and `get_user_access`

**To Reproduce**
N/A

**Expected behavior**
Both features should be documented under an "individual access" abstraction page

**Console Output**
N/A

**Environment Information:**
N/A

**Additional context**
N/A

**Comment by lcarcaramo** [comment]
Resolved by #74 & #76
